### Get all currencies - 200 OK
GET http://localhost:8080/currencies/
Accept:  application/json;charset=UTF-8

### Get certain currency - 200 OK
GET http://localhost:8080/currency/USD
Accept:  application/json;charset=UTF-8

### Get invalid currency - 400 Bad request
GET http://localhost:8080/currency/US
Accept:  application/json;charset=UTF-8

### Add new currency - 201 OK
POST http://localhost:8080/currencies/
Content-Type: application/x-www-form-urlencoded

code=EUR &
sign=E &
fullName=European Currency

### Add invalid code in currency
POST http://localhost:8080/currencies/
Content-Type: application/x-www-form-urlencoded

code=EU &
sign=€ &
fullName=European Currency

### Add invalid sign in currency
POST http://localhost:8080/currencies/
Content-Type: application/x-www-form-urlencoded

code=EUR &
sign=€f &
fullName=European Currency


### Get all exchange rates
GET http://localhost:8080/exchangeRates/
Accept:  application/json;charset=UTF-8

### Get exchange rate between two currencies
GET http://localhost:8080/exchangeRate/USDRUB
Accept:  application/json;charset=UTF-8

### Try to get exchange rate between invalid currencies
GET http://localhost:8080/exchangeRate/USDRU
Accept:  application/json;charset=UTF-8

### Try to get exchange rate with empty currencies
GET http://localhost:8080/exchangeRate/
Accept:  application/json;charset=UTF-8

### Get exchange amount between two currencies
GET http://localhost:8080/exchange?from=AUD&to=USD&amount=10

### Try to get exchange amount with first invalid currency
GET http://localhost:8080/exchange?from=AU&to=USD&amount=10

### Try to get exchange amount with second invalid currency
GET http://localhost:8080/exchange?from=AUD&to=US&amount=10

### Try to get exchange amount with invalid amount
GET http://localhost:8080/exchange?from=AUD&to=USD&amount=U

### Try to get exchange amount with empty arguments
GET http://localhost:8080/exchange?from=&to=&amount=